# Generated by Django 3.1.2 on 2020-11-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbcustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusname', models.CharField(max_length=100)),
                ('custel', models.CharField(max_length=30)),
                ('cusaddress', models.CharField(max_length=100)),
                ('cusdes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tbfttx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fttx', models.CharField(max_length=10)),
                ('fttxdes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tblli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lli', models.CharField(max_length=10)),
                ('lliip', models.CharField(max_length=50)),
                ('llides', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tbsafelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slgsn', models.CharField(max_length=50)),
                ('slgcputype', models.CharField(max_length=50)),
                ('slgcliamin', models.DateField()),
                ('slgcliamout', models.DateField()),
                ('slgdesc', models.TextField()),
                ('admit', models.DateField(null=True)),
                ('slgtpye', models.CharField(blank=True, choices=[('J1900', '1900'), ('Corei5', 'Corei5')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upssn', models.CharField(max_length=50)),
                ('upsadmitdate', models.DateField()),
                ('upstype', models.CharField(blank=True, choices=[('850V', '850V'), ('1000V', '1000V'), ('1200V', '1200')], max_length=30, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
